[all]
node1    ansible_host=10.0.0.7 ansible_connection=ssh ansible_ssh_pass=84920000 ip=10.0.0.7
#node2    ansible_host=192.168.43.118 ansible_connection=ssh ansible_ssh_pass=84920000 ip=192.168.43.118
#node3    ansible_host=192.168.43.103 ansible_connection=ssh ansible_user=root ansible_ssh_pass=84920000 ip=192.168.43.103
node4    ansible_host=10.0.0.8 ansible_connection=ssh ansible_ssh_pass=84920000 ip=10.0.0.8
node5    ansible_host=10.0.0.9 ansible_connection=ssh ansible_ssh_pass=84920000 ip=10.0.0.9

[kube-master]
node1
#node2
#node3

[kube-node]

node1
#node2
#node3
node4
node5

[etcd]
node1
#node2
#node3

[k8s-cluster:children]
kube-node
kube-master

[calico-rr]

[vault]
node1
#node2
#node3


[all:vars]
ansible_user=root
kubelet_cgroup_driver=cgroupfs


