Vagrant.configure("2") do |config|

# Specifiec the box.  
  config.vm.box = "bento/centos-7.2"
  config.vm.box_version = "2.3.1"

# Provisioning via a shell script. (- For Docker.)
  config.vm.provision "shell", path: "docker_for_centos.sh"

end
